Update
allen11137/java-shareit pull request #1
Opened 2023-10-10 19:29 UTC by allen11137

2023-10-11 18:56 UTC, z8q requested changes

2023-10-11 18:56 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long ownerId;
В тз поле просят назвать просто owner. Не критично, но если в последующих домашках будут ошибки на тестах постмана, название поля может быть причиной

2023-10-11 18:56 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final List<Item> items = new ArrayList<>();
Почему решили использовать лист вместо мапы?
Чтобы найти объект в листе, нужно перебирать все элементы.
В мапе поиск происходит по ключу за константное время.

2023-10-11 18:56 UTC, z8q commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +@Slf4j
Тут логи не используем, аннотацию можно убрать

2023-10-11 18:56 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public ResponseEntity<?> updateUser(@PathVariable Long userId, @RequestBody UserDto userDto) {
Стоит привести возвращаемое значение к конкретному типу как в addUser
В методах ниже тоже

2023-10-11 18:56 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    private String email;
Почему не использовали в dto валидационные аннотации (Email, NotNull, NotBlank и др.)?

2023-10-11 18:56 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        throw new NotFoundException("Ошибка");
По описанию полученного сообщения будет сложно понять, в чем причина ошибки

2023-10-12 06:10 UTC, allen11137 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long ownerId;
Исправила

2023-10-12 06:10 UTC, allen11137 commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +@Slf4j
+

2023-10-12 06:17 UTC, allen11137 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        throw new NotFoundException("Ошибка");
+

2023-10-12 08:32 UTC, allen11137 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final List<Item> items = new ArrayList<>();
Готово

2023-10-12 08:33 UTC, allen11137 commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    private String email;
Готово

2023-10-12 08:51 UTC, allen11137 commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public ResponseEntity<?> updateUser(@PathVariable Long userId, @RequestBody UserDto userDto) {
Добавила

2023-10-12 19:17 UTC, z8q approved these changes

2023-10-12 19:17 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +@Valid
Обычно Valid ставят в аргументах контроллера:
```
addItem(@RequestHeader("X-Sharer-User-Id") Long userId, @RequestBody @Valid ItemDto itemDto)
```
Чтобы сразу показать, какие аргументы будут валидироваться

2023-10-19 18:26 UTC, merged