Update 29.10
allen11137/java-shareit pull request #2
Opened 2023-10-29 18:13 UTC by allen11137

2023-10-30 18:23 UTC, z8q requested changes

2023-10-30 18:23 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @NotNull
Валидационные аннотации следует использовать в дто. 
Сущности нужны для описания вида таблиц и для описания связей с другими сущностями.

2023-10-30 18:23 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    User getUserById(Long userId);
Если методы не используются, лучше убрать

2023-10-30 18:23 UTC, z8q commented on src/main/java/ru/practicum/shareit/controller/BookingController.java
> +package ru.practicum.shareit.controller;
нужно перенести в пакет ru.practicum.shareit.booking

2023-10-30 18:23 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>      public UserDto createUser(UserDto userDto) {
При попытке создания дубля пользователя приходит ошибка 500. Можно было бы отлавливать исключение и выводить ошибку с каким-нибудь описанием

2023-10-30 18:23 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>      public ItemDto createItem(Long userId, ItemDto itemDto) {
Когда создаем вещь с X-Sharer-User-Id несуществующего пользователя, приходит ошибка 404. Можно было бы перехватить и вывести понятное сообщение

2023-10-30 18:23 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      }
Удается сделать patch с пустыми полями
http://localhost:8080/items/1
```JSON
{
	"name": "",
	"description": "",
	"available": true
}
```

2023-10-30 18:23 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      }
В контроллере пользователей тоже удается

2023-10-30 18:23 UTC, z8q commented on src/main/java/ru/practicum/shareit/controller/BookingController.java
> +    public ResponseEntity<BookingDto> addBooking(@RequestBody BookingRequest request,
Если создаю бронирование с прошедшим временем, приходит просто 400, без описания

2023-10-30 18:23 UTC, z8q commented on src/main/java/ru/practicum/shareit/controller/BookingController.java
> +    public ResponseEntity<BookingDto> addBooking(@RequestBody BookingRequest request,
Нужны методы, помеченные `@ExceptionHandler` для обработки исключений

2023-10-30 18:23 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ResponseEntity<CommentResponseDto> addComment(@RequestHeader("X-Sharer-User-Id") Long userId,
Если комментарий пытается оставить пользователь, который не брал вещь в аренду. Можно было бы тоже вывести соответствующее сообщение. Сейчас приходит просто 400

2023-10-30 18:23 UTC, z8q commented on src/main/java/ru/practicum/shareit/controller/BookingController.java
> +    public ResponseEntity<?> getAllBooking(@RequestParam(defaultValue = "ALL") BookingState state,
Стоит поставить конкретный тип

2023-10-30 18:23 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findBookingsByItem_OwnerIdAndStatusInAndEndBeforeOrderByStartDesc(Long bookerId, List<Status> status, LocalDateTime end);
Если название метода становится слишком длинным, в коде его становится неудобно использовать.
В таких случаях лучше использовать `@Query`.
Это больше как пожелание

2023-10-30 18:23 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/dto/BookingItemDtoResponse.java
> +    private LocalDateTime start;
Для полей с датами можно еще использовать `@JsonFormat` для того, чтобы задавать нужный формат

2023-10-30 19:20 UTC, allen11137 commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    User getUserById(Long userId);
Готово

2023-10-30 19:21 UTC, allen11137 commented on src/main/java/ru/practicum/shareit/controller/BookingController.java
> +package ru.practicum.shareit.controller;
Готово

2023-10-30 19:24 UTC, allen11137 commented on src/main/java/ru/practicum/shareit/controller/BookingController.java
> +    public ResponseEntity<?> getAllBooking(@RequestParam(defaultValue = "ALL") BookingState state,
Готово

2023-10-30 19:35 UTC, allen11137 commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @NotNull
Готово

2023-10-30 19:40 UTC, allen11137 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      }
Добавила валидационные аннотации

2023-10-30 20:01 UTC, allen11137 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>      public UserDto createUser(UserDto userDto) {
Готово

2023-10-30 20:09 UTC, allen11137 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>      public ItemDto createItem(Long userId, ItemDto itemDto) {
Не совсем понимаю вопрос, на строке 43-44 проверка на то, что пользователь не найден и сообщение об этом в формате "Пользователь не найден"/

2023-10-30 20:59 UTC, allen11137 commented on src/main/java/ru/practicum/shareit/controller/BookingController.java
> +    public ResponseEntity<BookingDto> addBooking(@RequestBody BookingRequest request,
Исправила

2023-10-30 21:22 UTC, allen11137 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ResponseEntity<CommentResponseDto> addComment(@RequestHeader("X-Sharer-User-Id") Long userId,
Добавила

2023-10-31 18:44 UTC, z8q approved these changes

2023-10-31 20:37 UTC, merged